version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hrbot
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  bot:
    build: .
    env_file: .env          # DATABASE_URL и др.
    depends_on:
      db:
        condition: service_healthy   # ждём healthcheck PG
    restart: unless-stopped

volumes:
  db_data:
